{{- if eq .Values.db.dbType "adb" -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: db-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  PG_HOST: "{{ .Values.db.adb.pgHost }}"
  PG_PORT: "{{ .Values.db.adb.pgPort }}"
  PG_DATABASE: "{{ .Values.db.adb.pgDataBase }}"
  PG_USER: "{{ .Values.db.adb.pgUser }}"
  PG_PASSWORD: "{{ .Values.db.adb.pgPassword }}"
{{- end -}}