apiVersion: v1
kind: Service
metadata:
  name: llm-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  {{- with $annotations := .Values.llm.service.annotations }}
  annotations: {{- toYaml $annotations | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: api
      port: 8888
      targetPort: 8888
    - name: fc-controller
      port: 20001
      targetPort: 20001
  selector: {{ include "llm.matchLabels" . | nindent 4 }}
  type: {{ .Values.llm.service.type }}