apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stable-diffusion
  name: stable-diffusion
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stable-diffusion
  template:
    metadata:
      labels:
        app: stable-diffusion
      annotations:
        k8s.aliyun.com/eci-use-specs: ecs.gn6i-c8g1.2xlarge,ecs.gn5-c8g1.2xlarge,ecs.gn6v-c8g1.8xlarge,ecs.gn6i-c16g1.4xlarge
    spec:
      containers:
        - args:
            - --listen
          command:
            - python3
            - launch.py
          image: kube-ai-registry.cn-shanghai.cr.aliyuncs.com/kube-ai/stable-diffusion:v1.4.0
          imagePullPolicy: IfNotPresent
          name: stable-diffusion
          ports:
            - containerPort: 7860
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 7860
          resources:
            limits:
              cpu: "8"
              memory: 16Gi
              ephemeral-storage: 50Gi
---
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-address-type: internet
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-instance-charge-type: PayByCLCU
  name: stable-diffusion-svc
  namespace: default
spec:
  externalTrafficPolicy: Local
  ports:
    - port: 7860
      protocol: TCP
      targetPort: 7860
  selector:
    app: stable-diffusion
  type: ClusterIP