apiVersion: v1
kind: Service
metadata:
  name: vllm-service
  namespace: default
spec:
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: vllm
  type: ClusterIP